// mockData.ts
export const mockNewsData = [
    {
      summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
      headline: "Sample Headline",
      source: "Mock Source",
      url: "https://example.com",
      image: "/placeholder.svg",
      category: "Mock Category",
    },
    {
        summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
        headline: "Sample Headline",
        source: "Mock Source",
        url: "https://example.com",
        image: "/placeholder.svg",
        category: "Mock Category",
      },
      {
        summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
        headline: "Sample Headline",
        source: "Mock Source",
        url: "https://example.com",
        image: "/placeholder.svg",
        category: "Mock Category",
      },
      {
        summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
        headline: "Sample Headline",
        source: "Mock Source",
        url: "https://example.com",
        image: "/placeholder.svg",
        category: "Mock Category",
      },
      {
        summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
        headline: "Sample Headline",
        source: "Mock Source",
        url: "https://example.com",
        image: "/placeholder.svg",
        category: "Mock Category",
      },
      {
        summary: "<strong>Google's Taara Initiative</strong><ul><li>Google's **Taara** project is an ambitious effort aimed at providing **high-speed internet connectivity** using **light-based technology**.<ul><li>Traditional internet connections often rely on **fiber optics** and **satellite technology**, but Taara seeks to use **free-space optical communication**, which can transmit data through air using laser beams.</li><li>This system aims to enhance internet access, particularly in **rural** and **under-served areas** where traditional infrastructure is either too costly or impractical to set up.</li></ul></li><li>Taara's technology has already shown promising results in **testing phases**, demonstrating its ability to deliver **high-speed internet** across significant distances without the need for physical cabling.<ul><li>The project leverages **light** to achieve speeds comparable to fiber optics, which could lead to faster connections and more reliable internet service for users.</li><li>Challenges such as **weather conditions** and ***line of sight** limitations are being addressed to ensure the technology's effectiveness in diverse environments.</li></ul></li></ul><strong>Future Implications</strong><ul><li>If successful, Taara could revolutionize the way internet is delivered globally by making it more **accessible and affordable**.<ul><li>This could pave the way for new economic opportunities and improved communication in areas that currently lack reliable connectivity.</li><li>Ultimately, Taara aims to bridge the **digital divide**, ensuring that more people have access to the **benefits of the internet**.</li></ul></li></ul>",
        headline: "Sample Headline",
        source: "Mock Source",
        url: "https://example.com",
        image: "/placeholder.svg",
        category: "Mock Category",
      },
  ];
  
